project_id = "mfxuocwjbtymmfjxtjti"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.handle-unsubscribe]
    verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.agent-api]
verify_jwt = false

[functions.delete-account]
verify_jwt = true
