/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as EmailUnsubscribeRouteImport } from './routes/email-unsubscribe'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReferralRewardsRouteImport } from './routes/referral-rewards'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SponsorsPartnersRouteImport } from './routes/sponsors-partners'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBulkActionsRouteImport } from './routes/admin/bulk-actions'
import { Route as AdminCheckinRouteImport } from './routes/admin/checkin'
import { Route as AdminCommunicationsRouteImport } from './routes/admin/communications'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminEsgRouteImport } from './routes/admin/esg'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminIntrosRouteImport } from './routes/admin/intros'
import { Route as AdminLionsRouteImport } from './routes/admin/lions'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as LionsIndexRouteImport } from './routes/lions/index'
import { Route as LionsApplyRouteImport } from './routes/lions/apply'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as TicketsFlagshipRouteImport } from './routes/tickets/flagship'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email-unsubscribe',
  path: '/email-unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRewardsRoute = ReferralRewardsRouteImport.update({
  id: '/referral-rewards',
  path: '/referral-rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsPartnersRoute = SponsorsPartnersRouteImport.update({
  id: '/sponsors-partners',
  path: '/sponsors-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBulkActionsRoute = AdminBulkActionsRouteImport.update({
  id: '/admin/bulk-actions',
  path: '/admin/bulk-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/admin/checkin',
  path: '/admin/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/admin/communications',
  path: '/admin/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEsgRoute = AdminEsgRouteImport.update({
  id: '/admin/esg',
  path: '/admin/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntrosRoute = AdminIntrosRouteImport.update({
  id: '/admin/intros',
  path: '/admin/intros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLionsRoute = AdminLionsRouteImport.update({
  id: '/admin/lions',
  path: '/admin/lions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LionsIndexRoute = LionsIndexRouteImport.update({
  id: '/lions/',
  path: '/lions/',
  getParentRoute: () => rootRouteImport,
} as any)
const LionsApplyRoute = LionsApplyRouteImport.update({
  id: '/lions/apply',
  path: '/lions/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsFlagshipRoute = TicketsFlagshipRouteImport.update({
  id: '/tickets/flagship',
  path: '/tickets/flagship',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/email-unsubscribe': typeof EmailUnsubscribeRoute
  '/esg': typeof EsgRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/referral-rewards': typeof ReferralRewardsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sponsors-partners': typeof SponsorsPartnersRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk-actions': typeof AdminBulkActionsRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/intros': typeof AdminIntrosRoute
  '/admin/lions': typeof AdminLionsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/lions/apply': typeof LionsApplyRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tickets/flagship': typeof TicketsFlagshipRoute
  '/admin/': typeof AdminIndexRoute
  '/lions/': typeof LionsIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/email-unsubscribe': typeof EmailUnsubscribeRoute
  '/esg': typeof EsgRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/referral-rewards': typeof ReferralRewardsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sponsors-partners': typeof SponsorsPartnersRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk-actions': typeof AdminBulkActionsRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/intros': typeof AdminIntrosRoute
  '/admin/lions': typeof AdminLionsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/lions/apply': typeof LionsApplyRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tickets/flagship': typeof TicketsFlagshipRoute
  '/admin': typeof AdminIndexRoute
  '/lions': typeof LionsIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/email-unsubscribe': typeof EmailUnsubscribeRoute
  '/esg': typeof EsgRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/referral-rewards': typeof ReferralRewardsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sponsors-partners': typeof SponsorsPartnersRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk-actions': typeof AdminBulkActionsRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/intros': typeof AdminIntrosRoute
  '/admin/lions': typeof AdminLionsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/lions/apply': typeof LionsApplyRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tickets/flagship': typeof TicketsFlagshipRoute
  '/admin/': typeof AdminIndexRoute
  '/lions/': typeof LionsIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/directory'
    | '/email-unsubscribe'
    | '/esg'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/referral-rewards'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sponsors-partners'
    | '/unsubscribe'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/bulk-actions'
    | '/admin/checkin'
    | '/admin/communications'
    | '/admin/enquiries'
    | '/admin/esg'
    | '/admin/events'
    | '/admin/intros'
    | '/admin/lions'
    | '/admin/members'
    | '/admin/settings'
    | '/lions/apply'
    | '/messages/$conversationId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/tickets/flagship'
    | '/admin/'
    | '/lions/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/directory'
    | '/email-unsubscribe'
    | '/esg'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/referral-rewards'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sponsors-partners'
    | '/unsubscribe'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/bulk-actions'
    | '/admin/checkin'
    | '/admin/communications'
    | '/admin/enquiries'
    | '/admin/esg'
    | '/admin/events'
    | '/admin/intros'
    | '/admin/lions'
    | '/admin/members'
    | '/admin/settings'
    | '/lions/apply'
    | '/messages/$conversationId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/tickets/flagship'
    | '/admin'
    | '/lions'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/directory'
    | '/email-unsubscribe'
    | '/esg'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/referral-rewards'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sponsors-partners'
    | '/unsubscribe'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/bulk-actions'
    | '/admin/checkin'
    | '/admin/communications'
    | '/admin/enquiries'
    | '/admin/esg'
    | '/admin/events'
    | '/admin/intros'
    | '/admin/lions'
    | '/admin/members'
    | '/admin/settings'
    | '/lions/apply'
    | '/messages/$conversationId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/tickets/flagship'
    | '/admin/'
    | '/lions/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DirectoryRoute: typeof DirectoryRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EsgRoute: typeof EsgRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferralRewardsRoute: typeof ReferralRewardsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SponsorsPartnersRoute: typeof SponsorsPartnersRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBulkActionsRoute: typeof AdminBulkActionsRoute
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminEsgRoute: typeof AdminEsgRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminIntrosRoute: typeof AdminIntrosRoute
  AdminLionsRoute: typeof AdminLionsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  LionsApplyRoute: typeof LionsApplyRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  TicketsFlagshipRoute: typeof TicketsFlagshipRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LionsIndexRoute: typeof LionsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-unsubscribe': {
      id: '/email-unsubscribe'
      path: '/email-unsubscribe'
      fullPath: '/email-unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral-rewards': {
      id: '/referral-rewards'
      path: '/referral-rewards'
      fullPath: '/referral-rewards'
      preLoaderRoute: typeof ReferralRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors-partners': {
      id: '/sponsors-partners'
      path: '/sponsors-partners'
      fullPath: '/sponsors-partners'
      preLoaderRoute: typeof SponsorsPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bulk-actions': {
      id: '/admin/bulk-actions'
      path: '/admin/bulk-actions'
      fullPath: '/admin/bulk-actions'
      preLoaderRoute: typeof AdminBulkActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/admin/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/admin/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/esg': {
      id: '/admin/esg'
      path: '/admin/esg'
      fullPath: '/admin/esg'
      preLoaderRoute: typeof AdminEsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/intros': {
      id: '/admin/intros'
      path: '/admin/intros'
      fullPath: '/admin/intros'
      preLoaderRoute: typeof AdminIntrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lions': {
      id: '/admin/lions'
      path: '/admin/lions'
      fullPath: '/admin/lions'
      preLoaderRoute: typeof AdminLionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lions/': {
      id: '/lions/'
      path: '/lions'
      fullPath: '/lions/'
      preLoaderRoute: typeof LionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lions/apply': {
      id: '/lions/apply'
      path: '/lions/apply'
      fullPath: '/lions/apply'
      preLoaderRoute: typeof LionsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/flagship': {
      id: '/tickets/flagship'
      path: '/tickets/flagship'
      fullPath: '/tickets/flagship'
      preLoaderRoute: typeof TicketsFlagshipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DirectoryRoute: DirectoryRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EsgRoute: EsgRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReferralRewardsRoute: ReferralRewardsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SponsorsPartnersRoute: SponsorsPartnersRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBulkActionsRoute: AdminBulkActionsRoute,
  AdminCheckinRoute: AdminCheckinRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminEsgRoute: AdminEsgRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminIntrosRoute: AdminIntrosRoute,
  AdminLionsRoute: AdminLionsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  LionsApplyRoute: LionsApplyRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  TicketsFlagshipRoute: TicketsFlagshipRoute,
  AdminIndexRoute: AdminIndexRoute,
  LionsIndexRoute: LionsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
